export const ALL_POST_REQUEST = "POST_REQUEST";
export const ALL_POST_SUCCESS = "POST_SUCCESS";
export const ALL_POST_FAIL = "POST_FAIL";


export const POST_DETAILS_REQUEST = "POST_DETAILS_REQUEST";
export const POST_DETAILS_SUCCESS = "POST_DETAILS_SUCCESS";
export const POST_DETAILS_FAIL = "POST_DETAILS_FAIL";



export const ADMIN_POST_REQUEST = "ADMIN_POST_REQUEST";
export const ADMIN_POST_SUCCESS = "ADMIN_POST_SUCCESS";
export const ADMIN_POST_FAIL = "ADMIN_POST_FAIL";

export const NEW_POST_REQUEST = "NEW_POST_REQUEST";
export const NEW_POST_SUCCESS = "NEW_POST_SUCCESS";
export const NEW_POST_RESET = "NEW_POST_RESET";
export const NEW_POST_FAIL = "NEW_POST_FAIL";

export const UPDATE_POST_REQUEST = "UPDATE_POST_REQUEST";
export const UPDATE_POST_SUCCESS = "UPDATE_POST_SUCCESS";
export const UPDATE_POST_RESET = "UPDATE_POST_RESET";
export const UPDATE_POST_FAIL = "UPDATE_POST_FAIL";

export const DELETE_POST_REQUEST = "DELETE_POST_REQUEST";
export const DELETE_POST_SUCCESS = "DELETE_POST_SUCCESS";
export const DELETE_POST_RESET = "DELETE_POST_RESET";
export const DELETE_POST_FAIL = "DELETE_POST_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";